# Don't print a new line at the start of the prompt
add_newline = true

[username]
disabled = false

[character]      # The name of the module we are configuring is "character"
error_symbol = "[❯](bold red)"
success_symbol = "[➜](bold green)"
vicmd_symbol = " ❮"

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
style = "bold blue"

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
